### ISSUE TITLE
!dadjoke command does not include a joke!

### ISSUE THREAD

**Issue by fuzzzerd** [dmoczisko/dampes-ghost#1]
The `!dadjoke` command does not include a joke, it only sends a gif.

**Comment by krybarczyk5** [comment]
Thank you for your feedback. This is a known issue and is being looked into.

**Comment by fuzzzerd** [comment]
Confirmed, thanks!

**Comment by dmoczisko** [comment]
Resolved in 0241028657071f0bc5eb1806292b37713650ca24
